{% set name = "elyra-r-editor-extension" %}
{% set version = "3.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra-r-editor-extension-{{ version }}.tar.gz
  sha256: 282877fc378b2eb4d392b91a511d14ceea147403c1e5fd1e8c97711c4706cb80

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - jupyter_packaging
    - pip
  run:
    - python >=3.7
    - elyra-server =={{ version }}
    - jupyter_packaging

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra provides AI Centric extensions to JupyterLab
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - kiersten-stokes
