{% set name = "elyra-r-editor-extension" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 14ef16195fe24bdd0181080ff2b1315f5b854c722670075a2dc6cb2dddf4dc85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - jupyter_packaging
    - pip
  run:
    - python >=3.8
    - elyra-server =={{ version }}
    - jupyter_packaging

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra provides AI Centric extensions to JupyterLab
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - kiersten-stokes
