{% set name = "elyra-r-editor-extension" %}
{% set version = "3.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra-r-editor-extension-{{ version }}.tar.gz
  sha256: 4e36a905b67ccc9de27aba097dc7e9e488a301997c70319f0bbd083b3781b008

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - jupyter_packaging
    - pip
  run:
    - python >=3.8
    - elyra-server =={{ version }}
    - jupyter_packaging

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra provides AI Centric extensions to JupyterLab
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - kiersten-stokes
