{% set name = "elyra-r-editor-extension" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f9159510b248d5275d052e9e7113a7119ef4ac8c40cebf2321b91abd59a19d98

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - jupyter_packaging
    - pip
  run:
    - python >=3.8
    - elyra-server =={{ version }}
    - jupyter_packaging

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra provides AI Centric extensions to JupyterLab
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - kiersten-stokes
